### ISSUE TITLE
Error: stream ended with:0 but wanted:64

### ISSUE THREAD

**Issue by KGibb8** [blockades/dark-crystal-standalone#10]
When starting the app, some of the time we're unable to successfully connect to ssb-server.

```
server error, from net:::ffff:127.0.0.1:33731~shs:
Error: stream ended with:0 but wanted:64
    at drain (/home/kyphae/Projects/dark-crystal-standalone/node_modules/ssb-server/node_modules/pull-reader/index.js:43:26)
    at /home/kyphae/Projects/dark-crystal-standalone/node_modules/ssb-server/node_modules/pull-reader/index.js:63:18
    at /home/kyphae/Projects/dark-crystal-standalone/node_modules/ssb-server/node_modules/pull-reader/index.js:20:7
    at drain (/home/kyphae/Projects/dark-crystal-standalone/node_modules/ssb-server/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/home/kyphae/Projects/dark-crystal-standalone/node_modules/ssb-server/node_modules/stream-to-pull-stream/index.js:162:5)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:554:12)
```

**Comment by KGibb8** [comment]
@mixmix or @ameba23 either of your eyes on this would be helpful.

**Comment by heroims** [comment]
I had the same problem, did you solve it?
